add remaining steps in orthomclSampleRun
git-svn-id: https://cbilsvn.pmacs.upenn.edu/svn/apidb/OrthoMCLEngine/branches/2.0-bundle-msh@30709 735e2a04-f8fc-0310-8a1b-f2942603c481

diff --git a/Main/bin/orthomclSampleRun b/Main/bin/orthomclSampleRun
--- a/Main/bin/orthomclSampleRun
+++ b/Main/bin/orthomclSampleRun
@@ -61,3 +61,14 @@ echo "running orthomclDumpPairsFiles"
 orthomclDumpPairsFiles $WORK_DIR/orthomcl.config
 [[ "$?" -eq "0" ]] || { echo "FAILED"; exit 1; }
 
+
+echo "running mcl"
+mcl $WORK_DIR/mclInput  --abc -I 1.5 -o $WORK_DIR/mclOutput
+[[ "$?" -eq "0" ]] || { echo "FAILED"; exit 1; }
+
+
+echo "running orthomclMclToGroups"
+orthomclMclToGroups MSH_ 1 $WORK_DIR/mclOutput
+[[ "$?" -eq "0" ]] || { echo "FAILED"; exit 1; }
+
+echo "done"
